### ISSUE TITLE
feat(benchmarks): Benchmark Maintenance

### ISSUE THREAD

**Issue by PatStiles** [lambdaclass/lambdaworks#588]
The current benchmarks within lambdaworks/math need a round of updating. Based on conversation with @MauroToscano this issue seeks to outline updating the current benchmark suite in lambdaworks/math:
 
 Lambdaworks currently has benchmarks that:
 - Compare all field operations of a specific field that benchmark the execution of one field operation against a set of pre-determined field elements. Currently these operations are not black boxed so the compiler is optimizing them away.
 - Compare all operations on polynomials of different random coefficients of a preset order. These coefficient differ across all polynomial operation benchmarks.
 - Measure the performance of the Ate pairing operation for BLS12-381.
 - Comparing field operations against [Arkworks]() grouped by field operations and benchmark the execution of 1000 operations on a vector of random field elements. Both operations in lambdaworks and arkworks benchmark against the same randomly generated data and are properly black boxed.

At a high level we want our benchmarks to:
- Be canonical and easy to adapt so new contributors can easily extend them by copying pre existing benchmarks and adapting them to there needs.
- Demonstrate proper compiler awareness and [blackboxing](https://gendignoux.com/blog/2022/01/31/rust-benchmarks.html)
- Perform comparisons across random inputs to prevent any bias in input values (operating on some values such as the neutral element of a curve could be easier than other)
- Benchmark across different input size to determine to demonstrate operations are constant time. Note this ideally would be toggled (Note see [constantine](https://github.com/mratsim/constantine/pull/220) benchmark output )
- Have all benchmarks operates on the same randomly generative values allowing for proper comparison.

This issue tracks the task of improving the benchmarks for Fields, Polynomials, Curves, and other cryptography libraries.

# Tasks:

## src/benches:

- [ ] Refactor to use variable length random input
- [ ] Use same random input values across all benchmarks being performed
- [ ] Extend to compare lambdaworks against other libraries: [gnark](https://github.com/Consensys/gnark-crypto/tree/ed8216091919174f8d578ef1f023ebcb649df7fa), [zkcrypto](https://github.com/zkcrypto), [dalek](https://github.com/dalek-cryptography/curve25519-dalek), [halo2-curves](https://github.com/privacy-scaling-explorations/halo2curves), [blsts](https://github.com/filecoin-project/blstrs), and [constantine](https://github.com/mratsim/constantine).

## math/benches/criterion_fields
- [ ] Refactor into subdirectory with each field being a separate file
- [ ] Add proper black boxing
- [ ] Refactor to bench using variable length random input
- [ ] Use same random input values across all benchmarks being performed
- [ ] Split into multiple files based on field that bench all field operations

## math/benches/criterion_polynomial:
- [ ] Add proper black boxing
- [ ] Bench against variable length random input

## math/benches/criterion_elliptic_curves:
- [ ] Add benchmarks for all curve operations
- [ ] Refactor into subdirectory with each curve being a separate file
- [ ] Add proper black boxing
- [ ] Bench against variable length random input
- [ ] Split into multiple files based on curve that bench all curve operations

## General:
- [ ] Refactor the benchmarks to perform operations across different numbers of randomized inputs
- [ ] Ensure all benchmarks use proper black boxing
- [ ] Feature gate to allow for benchmarking all input sizes or one (Note: this needs further investigation)
- [ ] Create a readme and guide for contributors on adding benchmarks to lambdaworks explaining rational, footguns, and best practices.
- [ ] Lambdaworks to [zkalc](https://github.com/mmaker/zkalc) to actively support verification of these benchmarks by a third party.
